"""Prove the cameras observe one common geometry, and report what each sees.

This does the checks that *can* be automated. It deliberately does not claim to
judge realism - the specification is explicit that automated tests support
visual inspection rather than replacing it, and nothing here says whether the
result looks good.

What it does establish:

* every camera is inside the room and not inside furniture
* every camera shares one sensor, one exposure and one resolution - a cut
  between two different colour pipelines is a hard fail
* the SAME canonical 3D landmarks project into each camera, which is the actual
  evidence that there is one world rather than seven
* which landmarks each camera can see, which is the object visibility log the
  specification asks for
* the human transform is identical across cameras at a frozen timestamp,
  because the world is built once before any camera is asked for a picture

Writes `docs/multicam_validation.md`.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "tools"))


def project(scene, cam_ob, point):
    """World point -> (u, v) in 0..1 with v measured from the top, plus depth."""
    from bpy_extras.object_utils import world_to_camera_view
    from mathutils import Vector

    co = world_to_camera_view(scene, cam_ob, Vector(point))
    return co.x, 1.0 - co.y, co.z


def visibility(u, v, depth):
    if depth <= 0:
        return "behind"
    if 0.0 <= u <= 1.0 and 0.0 <= v <= 1.0:
        return "Y"
    if -0.25 <= u <= 1.25 and -0.25 <= v <= 1.25:
        return "P"
    return "N"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--time", type=float, default=314.5)
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--out", default="docs/multicam_validation.md")
    args = ap.parse_args()

    from render_multicam import frozen_pose

    import bpy
    from presenter.scene3d.world import build_world

    pose, _ = frozen_pose(args.time, seed=args.seed)
    world = build_world(pose)
    scene = bpy.context.scene

    lines: list[str] = []
    add = lines.append
    add("# Multi-camera consistency validation\n")
    add(f"Generated by `tools/validate_multicam.py` at simulation time "
        f"**T = {args.time:.3f} s**, seed {args.seed}.\n")
    add("Automated checks only. They establish that one world is being "
        "projected; they say nothing about whether it looks real.\n")

    add(f"\n## Scene\n")
    add(f"- scene_version: **{world.g['scene_version']}**")
    add(f"- room: {world.g['room']['width']} x {world.g['room']['depth']} x "
        f"{world.g['room']['height']} m")
    add(f"- objects in scene: {len(bpy.data.objects)}")
    add(f"- canonical landmarks tracked: {len(world.landmarks)}")

    add("\n## Frozen human state\n")
    add("Every camera renders *this* state. The world is built once, before any "
        "camera is asked for a picture, so the transforms cannot differ.\n")
    add("| quantity | value |")
    add("|---|---|")
    for name in ("yaw", "pitch", "roll", "eye_open_l", "eye_open_r",
                 "gaze_x", "gaze_y", "scale", "breathing_phase"):
        if hasattr(pose, name):
            add(f"| {name} | {getattr(pose, name):+.5f} |")

    add("\n## Camera rig\n")
    d = world.c["defaults"]
    add(f"Shared by every camera: sensor {d['sensor_width_mm']} x "
        f"{d['sensor_height_mm']} mm, exposure {d['exposure_ev']:+.1f} EV, "
        f"output {d['resolution'][0]}x{d['resolution'][1]}.\n")
    add("| camera | enabled | position | lens | f | focus dist |")
    add("|---|---|---|---|---|---|")
    for spec in world.c["cameras"]:
        ob = world.cameras[spec["id"]]
        p = spec["position"]
        add(f"| {spec['id']} | {'yes' if spec.get('enabled', True) else 'no'} | "
            f"({p[0]:+.2f}, {p[1]:+.2f}, {p[2]:+.2f}) | "
            f"{spec['focal_length_mm']:.0f} mm | f/{spec['f_stop']:.1f} | "
            f"{ob.data.dof.focus_distance:.2f} m |")

    problems = world.validate_cameras()
    add("\n## Camera placement\n")
    if problems:
        for p in problems:
            add(f"- **PROBLEM** {p}")
    else:
        add("All cameras inside the room and clear of furniture.")

    # -- the important one: shared landmark projection ---------------------
    interesting = [k for k in world.landmarks
                   if not k.startswith("slat_")] + ["slat_000", "slat_036",
                                                    "slat_071"]
    interesting = [k for k in interesting if k in world.landmarks]
    cams = [s["id"] for s in world.c["cameras"]]

    add("\n## Landmark projection - the evidence of one shared world\n")
    add("The same canonical 3D point projected through every camera. Different "
        "screen positions for the same world point are exactly what parallax "
        "is; identical world coordinates behind them are what makes it one "
        "room.\n")
    add("`Y` in frame, `P` just outside, `N` out of frame, `behind` the lens.\n")
    add("| landmark | world (x, y, z) | " + " | ".join(cams) + " |")
    add("|---|---|" + "---|" * len(cams))
    for name in sorted(interesting):
        pt = world.landmarks[name]
        cells = []
        for cid in cams:
            u, v, z = project(scene, world.cameras[cid], pt)
            vis = visibility(u, v, z)
            cells.append(f"{vis} ({u:.2f},{v:.2f})" if vis in ("Y", "P") else vis)
        add(f"| `{name}` | ({pt[0]:+.2f}, {pt[1]:+.2f}, {pt[2]:+.2f}) | "
            + " | ".join(cells) + " |")

    # -- parallax check ----------------------------------------------------
    add("\n## Parallax\n")
    add("A near landmark and a far landmark must separate differently between "
        "cameras. If both shift by the same amount the background is a flat "
        "picture, which is the failure this architecture exists to prevent.\n")
    near = "mic_main"
    far = "monitor_main"
    if near in world.landmarks and far in world.landmarks:
        add("| pair | cam1 | cam2 | cam3 |")
        add("|---|---|---|---|")
        row = []
        for cid in ("cam1", "cam2", "cam3"):
            if cid not in world.cameras:
                row.append("-")
                continue
            un, vn, _ = project(scene, world.cameras[cid], world.landmarks[near])
            uf, vf, _ = project(scene, world.cameras[cid], world.landmarks[far])
            row.append(f"{un - uf:+.3f}")
        add(f"| u({near}) - u({far}) | " + " | ".join(row) + " |")
        spread = max(float(x) for x in row if x != "-") - \
            min(float(x) for x in row if x != "-")
        add(f"\nSeparation varies by **{spread:.3f}** of frame width across the "
            f"three cameras. A flat backdrop would give 0.000.")

    out = ROOT / args.out
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[validate] -> {out}")
    if problems:
        print(f"[validate] {len(problems)} camera placement problem(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
