"""The comment -> response path, end to end, asserting the COMMENT trigger.

Written after a real failure. A viewer comment was ingested, the metric
incremented, and the session looked healthy -- but no reply was ever spoken,
because TTS was dead for an unrelated reason (a stale config naming a voice
that was not installed). Nothing in the suite noticed, because nothing asserted
that a comment produces a *comment-triggered* utterance.

That distinction is the whole point of this file. A host that happens to be
talking about gold when a viewer asks a question has not answered the question.
Every test here asserts on `TriggerType.COMMENT` specifically, so an utterance
generated by the education or market path can never satisfy it.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone

import pytest

from intelligence.director import Director, SpeechIntent
from intelligence.memory import SessionMemory
from platform_.adapters.filetail import FileTailAdapter
from shared.contracts import Priority, TriggerType


def now_utc() -> datetime:
    return datetime.now(timezone.utc)


def director() -> Director:
    return Director("SESSION_001", SessionMemory("SESSION_001"), max_silence_s=12.0)


# -- stage 1: adapter ------------------------------------------------------


def test_a_viewer_comment_becomes_a_comment_event(tmp_path):
    adapter = FileTailAdapter(session_id="SESSION_001", path=tmp_path / "c.txt")
    comment = adapter.parse("goldbug77: Neo, where do you think gold is heading?")

    assert comment is not None
    assert comment.text_raw == "Neo, where do you think gold is heading?"
    assert comment.session_id == "SESSION_001"
    assert "goldbug77" not in comment.author_hash, "handles must be hashed"


# -- stage 2: classification ----------------------------------------------


async def test_a_market_question_is_classified_and_kept(tmp_path):
    from intelligence.comments import CommentPipeline

    adapter = FileTailAdapter(session_id="SESSION_001", path=tmp_path / "c.txt")
    comment = adapter.parse("Neo, where do you think gold is heading?")
    assert comment is not None

    scored = await CommentPipeline("SESSION_001").process(comment)
    assert scored is not None, "a direct market question must not be dropped"
    assert scored.comment.classification is not None
    assert scored.priority >= Priority.MEDIUM


# -- stage 3: the Director must actually pick it --------------------------


def comment_intent(when: datetime, priority=Priority.HIGH) -> SpeechIntent:
    return SpeechIntent(
        trigger=TriggerType.COMMENT, priority=priority, topic="q:market_q",
        seed_text="where do you think gold is heading?", ttl_s=120.0,
        created_at=when,
        payload={"text": "Neo, where do you think gold is heading?",
                 "intent": "market_q", "is_risk_sensitive": False, "msg_id": "abc"},
    )


def education_intent(when: datetime) -> SpeechIntent:
    return SpeechIntent(
        trigger=TriggerType.EDUCATION, priority=Priority.LOW, topic="edu:spreads",
        seed_text="spreads", ttl_s=300.0, created_at=when,
    )


def test_a_comment_outscores_filler_content():
    """A viewer asking a question must beat whatever the host was going to say
    next, or replies arrive too late to be replies."""
    d = director()
    when = now_utc()

    comment_score, _ = d.score(comment_intent(when), when)
    edu_score, _ = d.score(education_intent(when), when)
    assert comment_score > edu_score


def test_the_director_selects_the_comment_over_education():
    d = director()
    when = now_utc()
    d.offer(education_intent(when))
    d.offer(comment_intent(when))

    decision = d.tick(now=when)
    assert decision is not None, "the comment must be selected, not deferred"
    assert decision.intent.trigger is TriggerType.COMMENT, (
        f"expected the COMMENT path, got {decision.intent.trigger} -- an "
        "education utterance is not an answer to a viewer's question"
    )


def test_a_comment_is_pending_until_it_is_spoken():
    d = director()
    when = now_utc()
    assert not d.has_pending(TriggerType.COMMENT)
    d.offer(comment_intent(when))
    assert d.has_pending(TriggerType.COMMENT)


def test_an_expired_comment_is_not_answered_late():
    """Answering a two-minute-old question is worse than not answering it."""
    d = director()
    when = now_utc()
    d.offer(comment_intent(when))
    decision = d.tick(now=when + timedelta(seconds=300))
    if decision is not None:
        assert decision.intent.trigger is not TriggerType.COMMENT


# -- stage 4: the whole chain, with the trigger asserted -------------------


async def test_on_comment_queues_a_comment_triggered_intent(tmp_path):
    """SessionRuntime.on_comment must produce an intent whose trigger is
    COMMENT -- the field the persisted utterance is stamped from, and the only
    evidence that a reply was a reply."""
    from intelligence.comments import CommentPipeline

    adapter = FileTailAdapter(session_id="SESSION_001", path=tmp_path / "c.txt")
    comment = adapter.parse("what is your view on the 4490 level?")
    assert comment is not None

    scored = await CommentPipeline("SESSION_001").process(comment)
    if scored is None:
        pytest.skip("classifier dropped the comment; covered by its own test")

    d = director()
    when = now_utc()
    cls = scored.comment.classification
    assert cls is not None
    d.offer(SpeechIntent(
        trigger=TriggerType.COMMENT, priority=scored.priority,
        topic=f"q:{cls.intent.value}", seed_text=scored.comment.text_norm,
        ttl_s=120.0, created_at=when,
        payload={"text": scored.comment.text_raw, "intent": cls.intent.value,
                 "is_risk_sensitive": cls.is_risk_sensitive,
                 "msg_id": scored.comment.platform_msg_id},
    ))

    decision = d.tick(now=when)
    assert decision is not None
    assert decision.intent.trigger is TriggerType.COMMENT
    assert decision.intent.payload["msg_id"] == comment.platform_msg_id, (
        "the reply must be traceable back to the comment that caused it"
    )


def test_comment_is_a_distinct_trigger_from_education_and_market():
    """Guards the assertion the other tests rest on: if these ever collapsed
    into one value, every test in this file would pass vacuously."""
    assert TriggerType.COMMENT != TriggerType.EDUCATION
    assert TriggerType.COMMENT != TriggerType.MARKET_EVENT
    assert TriggerType.COMMENT.value == "comment"


# -- background tasks must never die silently ------------------------------


def test_a_dead_background_task_turns_health_FAILING():
    """Regression from a real recovery test.

    Ollama was killed mid-session. The speak loop raised, the task ended, and
    because nothing ever retrieves a task's exception it did so in silence: the
    session stayed alive, produced nothing for eleven minutes, and /health went
    on reporting OK with /ready 200 -- so the supervisor had no reason to
    restart it. A crash would have been a better outcome than that.
    """

    from runtime.live import LiveSession
    from shared.contracts import HealthState

    app = LiveSession.__new__(LiveSession)
    app.session_id = "SESSION_001"
    app._task_failures = {}

    assert app._tasks_health().state is HealthState.OK

    app._task_failures["speak"] = "ConnectError: All connection attempts failed"
    health = app._tasks_health()
    assert health.state is HealthState.FAILING, (
        "a dead speak loop must make /ready return 503 so the supervisor acts"
    )
    assert "speak" in (health.degraded_reason or "")
    assert any(c.name == "speak" and not c.ok for c in health.checks)


def test_task_failures_are_recorded_with_the_exception():
    import asyncio

    from runtime.live import LiveSession

    app = LiveSession.__new__(LiveSession)
    app.session_id = "SESSION_001"
    app._task_failures = {}

    async def boom():
        raise ConnectionError("model server vanished")

    async def run():
        task = asyncio.create_task(boom(), name="speak")
        task.add_done_callback(app._on_task_done)
        with pytest.raises(ConnectionError):
            await task
        await asyncio.sleep(0)

    asyncio.run(run())
    assert "speak" in app._task_failures
    assert "model server vanished" in app._task_failures["speak"]


def test_a_cancelled_task_is_not_reported_as_a_failure():
    """Shutdown cancels every task; that must not look like a crash."""
    import asyncio

    from runtime.live import LiveSession

    app = LiveSession.__new__(LiveSession)
    app.session_id = "SESSION_001"
    app._task_failures = {}

    async def forever():
        await asyncio.sleep(3600)

    async def run():
        task = asyncio.create_task(forever(), name="speak")
        task.add_done_callback(app._on_task_done)
        task.cancel()
        with pytest.raises(asyncio.CancelledError):
            await task

    asyncio.run(run())
    assert app._task_failures == {}


def test_generation_health_reflects_a_dead_model_server():
    """Regression: killing Ollama left every health component green -- market,
    audio, adapter, session -- while the one thing the session exists to do was
    impossible. /ready stayed 200, so the supervisor never acted and the
    session sat mute for eleven minutes."""
    from runtime.live import LiveSession
    from shared.contracts import HealthState

    app = LiveSession.__new__(LiveSession)
    app.session_id = "SESSION_001"
    app._speak_errors = 0
    assert app._generation_health().state is HealthState.OK

    app._speak_errors = 2
    assert app._generation_health().state is HealthState.DEGRADED, (
        "a brief blip should degrade, not trigger a restart"
    )

    app._speak_errors = 11
    health = app._generation_health()
    assert health.state is HealthState.FAILING, (
        "sustained generation failure must make /ready 503 so the supervisor acts"
    )
    assert "model server" in (health.degraded_reason or "")
